# frozen_string_literal: true

source 'https://rubygems.org' 

gem 'rubocop'
gem 'rubocop-minitest'

gem 'rack'
gem 'logger'

gem 'rack-heartbeat'

gem 'minitest-power_assert'
gem 'rack-minitest'
gem 'rack-unreloader'
gem 'thin'
